site_name: Stow
# theme: readthedocs
theme:
    name: readthedocs
markdown_extensions:
    - tables
    - attr_list
    - admonition
    - pymdownx.details
    - pymdownx.superfences
# extra_css: [static/css/main.css]
nav:
    - Home: index.md
    - Managers: managers.md
    - Extending: extending.md
    - Changelog: changelog.md
    - Examples: examples.md
    # - CLI: cli.md
    - FAQ: faq.md
    - Reference:
        - stow: reference/stow.md
        - stow.manager: reference/stow.manager.md
        # - stow.managers: reference/stow.managers.md
        - stow.artefacts: reference/stow.artefacts.md
        - stow.exceptions: reference/stow.exceptions.md
plugins:
    - search # necessary for search to work
    # - mkapi
    - mkdocstrings