__version__ = "1.0.0-alpha"

from .artefacts import Artefact, File, Directory, SubFile, SubDirectory
from .manager import Manager, SubManager
from . import exceptions

from .stateless import (
    find,
    connect,
    parseURL,
    artefact,
    abspath,
    basename,
    commonpath,
    commonprefix,
    dirname,
    expanduser,
    expandvars,
    isabs,
    join,
    normcase,
    normpath,
    realpath,
    relpath,
    samefile,
    sameopenfile,
    samestat,
    split,
    splitdrive,
    splitext,
    md5,
    isfile,
    isdir,
    islink,
    ismount,
    getctime,
    getmtime,
    getatime,
    exists,
    lexists,
    touch,
    mkdir,
    localise,
    open,
    ls,
    get,
    put,
    cp,
    mv,
    sync,
    rm,
    supports_unicode_filenames,
)
